name: Rebuild
on:
  push:
    paths:
      - 'fragments/*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rebuild index.html
        run: sh rebuild.sh
      - name: Update repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add index.html
          git diff --cached --quiet || git commit -m "rebuilt index.html"
          git push -u origin gh-pages